# Generated by Django 5.2.9 on 2026-02-20 07:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("IRRIGATION", "IRRIGATION"),
                            ("SOIL_PH", "SOIL_PH"),
                            ("SOIL_EC", "SOIL_EC"),
                            ("SOIL_TEMP", "SOIL_TEMP"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("LOW", "LOW"), ("MED", "MED"), ("HIGH", "HIGH")],
                        max_length=8,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("message", models.TextField()),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="farm.field",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "IN_APP"),
                            ("WS", "WS"),
                            ("EMAIL", "EMAIL"),
                        ],
                        default="IN_APP",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SENT", "SENT"),
                            ("FAILED", "FAILED"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="soil_monitoring.recommendation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ts",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "moisture_vwc",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "ph",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(14.0),
                        ],
                    ),
                ),
                (
                    "ec_ds_m",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "soil_temp_c",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-50.0),
                            django.core.validators.MaxValueValidator(80.0),
                        ],
                    ),
                ),
                (
                    "depth_cm",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Sensor depth in cm", null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("sensor", "sensor"),
                            ("manual", "manual"),
                            ("test", "test"),
                        ],
                        default="sensor",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soil_readings",
                        to="farm.field",
                    ),
                ),
            ],
            options={
                "ordering": ["-ts"],
            },
        ),
        migrations.CreateModel(
            name="FieldSoilProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fc_vwc",
                    models.FloatField(
                        default=0.3,
                        help_text="Field Capacity (VWC 0..1)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "pwp_vwc",
                    models.FloatField(
                        default=0.15,
                        help_text="Permanent Wilting Point (VWC 0..1)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "mad",
                    models.FloatField(
                        default=0.5,
                        help_text="Management Allowed Depletion (0..1)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "ph_min",
                    models.FloatField(
                        default=6.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(14.0),
                        ],
                    ),
                ),
                (
                    "ph_max",
                    models.FloatField(
                        default=7.5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(14.0),
                        ],
                    ),
                ),
                (
                    "ec_max_ds_m",
                    models.FloatField(
                        default=4.0,
                        help_text="Max EC in dS/m before warnings",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("temp_min_c", models.FloatField(default=10.0)),
                ("temp_max_c", models.FloatField(default=35.0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soil_profile",
                        to="farm.field",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("fc_vwc__gt", models.F("pwp_vwc"))),
                        name="soilprofile_fc_gt_pwp",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ph_min__lt", models.F("ph_max"))),
                        name="soilprofile_ph_min_lt_ph_max",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("temp_min_c__lt", models.F("temp_max_c"))),
                        name="soilprofile_temp_min_lt_temp_max",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["field", "is_active", "-created_at"],
                name="soil_monito_field_i_35f911_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "status", "-created_at"],
                name="soil_monito_user_id_a16500_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recommendation", "-created_at"],
                name="soil_monito_recomme_e3be88_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=models.Index(
                fields=["field", "-ts"], name="soil_monito_field_i_228427_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sensorreading",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("moisture_vwc__isnull", True),
                    models.Q(("moisture_vwc__gte", 0.0), ("moisture_vwc__lte", 1.0)),
                    _connector="OR",
                ),
                name="reading_moisture_vwc_0_1_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="sensorreading",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ph__isnull", True),
                    models.Q(("ph__gte", 0.0), ("ph__lte", 14.0)),
                    _connector="OR",
                ),
                name="reading_ph_0_14_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="sensorreading",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ec_ds_m__isnull", True), ("ec_ds_m__gte", 0.0), _connector="OR"
                ),
                name="reading_ec_nonneg_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="sensorreading",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("soil_temp_c__isnull", True),
                    models.Q(("soil_temp_c__gte", -50.0), ("soil_temp_c__lte", 80.0)),
                    _connector="OR",
                ),
                name="reading_temp_range_or_null",
            ),
        ),
    ]
