# Generated by Django 5.2.9 on 2026-04-15 04:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoilMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "soil_type",
                    models.CharField(
                        choices=[
                            ("loamy", "Loamy"),
                            ("sandy", "Sandy"),
                            ("clay", "Clay"),
                            ("silty", "Silty"),
                            ("peaty", "Peaty"),
                            ("other", "Other"),
                        ],
                        default="loamy",
                        max_length=20,
                    ),
                ),
                (
                    "moisture_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "ph_level",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(14),
                        ],
                    ),
                ),
                (
                    "nitrogen",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Nitrogen value",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "phosphorus",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Phosphorus value",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "potassium",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Potassium value",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "temperature_celsius",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("sample_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soil_measurements",
                        to="farm.field",
                    ),
                ),
                (
                    "yield_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="soil_measurements",
                        to="farm.yieldrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-sample_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["field", "sample_date"],
                        name="soil_monito_field_i_880a8f_idx",
                    ),
                    models.Index(
                        fields=["soil_type"], name="soil_monito_soil_ty_eb0d33_idx"
                    ),
                    models.Index(
                        fields=["sample_date"], name="soil_monito_sample__8a81f4_idx"
                    ),
                ],
            },
        ),
    ]
