# Generated by Django 5.2.9 on 2026-02-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0001_initial"),
        ("soil_monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="recommendation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=models.Index(
                fields=["field", "source", "-ts"], name="soil_monito_field_i_4a458b_idx"
            ),
        ),
    ]
