# Generated by Django 5.2.9 on 2026-04-14 18:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "farm_code",
                    models.CharField(
                        blank=True,
                        help_text="Optional external farm ID like F001",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "size_hectares",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Farm size in hectares",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("species", models.CharField(max_length=50)),
                (
                    "tag_id",
                    models.CharField(
                        help_text="Unique ID for the animal (ear tag, etc.)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("sick", "Sick"),
                            ("critical", "Critical"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animals",
                        to="farm.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["species", "tag_id"],
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Field area in hectares",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "soil_type",
                    models.CharField(
                        choices=[
                            ("loamy", "Loamy"),
                            ("sandy", "Sandy"),
                            ("clay", "Clay"),
                            ("silty", "Silty"),
                            ("peaty", "Peaty"),
                            ("other", "Other"),
                        ],
                        default="loamy",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Field center latitude",
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Field center longitude",
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "polygon",
                    models.JSONField(
                        blank=True,
                        help_text="Optional polygon as [[lon, lat], [lon, lat], ...]. Auto-closed on save.",
                        null=True,
                    ),
                ),
                (
                    "bbox_min_lon",
                    models.FloatField(blank=True, editable=False, null=True),
                ),
                (
                    "bbox_max_lon",
                    models.FloatField(blank=True, editable=False, null=True),
                ),
                (
                    "bbox_min_lat",
                    models.FloatField(blank=True, editable=False, null=True),
                ),
                (
                    "bbox_max_lat",
                    models.FloatField(blank=True, editable=False, null=True),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="farm.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("plant_date", models.DateField(blank=True, null=True)),
                ("expected_harvest_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("growing", "Growing"),
                            ("harvested", "Harvested"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crops",
                        to="farm.field",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("watering", "Watering"),
                            ("fertilizing", "Fertilizing"),
                            ("feeding", "Feeding"),
                            ("harvesting", "Harvesting"),
                            ("vet_check", "Vet Check"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="farm.animal",
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="farm.crop",
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="farm.farm",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="farm.field",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("bio", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YieldRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_type", models.CharField(max_length=100)),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("kharif", "Kharif"),
                            ("rabi", "Rabi"),
                            ("zaid", "Zaid"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "irrigation_type",
                    models.CharField(
                        choices=[
                            ("drip", "Drip"),
                            ("sprinkler", "Sprinkler"),
                            ("manual", "Manual"),
                            ("flood", "Flood"),
                            ("rainfed", "Rain-fed"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "soil_type",
                    models.CharField(
                        choices=[
                            ("loamy", "Loamy"),
                            ("sandy", "Sandy"),
                            ("clay", "Clay"),
                            ("silty", "Silty"),
                            ("peaty", "Peaty"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "farm_area_acres",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "fertilizer_used_tons",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "pesticide_used_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "water_usage_cubic_meters",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "actual_yield_tons",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Real yield from dataset or from actual harvest",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "predicted_yield_tons",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="ML predicted yield",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100)),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional confidence in percent",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("prediction_created_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yield_records",
                        to="farm.farm",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="yield_records",
                        to="farm.field",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("code_hash", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("attempts_left", models.PositiveSmallIntegerField(default=5)),
                ("used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "used", "created_at"],
                        name="farm_emailo_email_0de82c_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="farm_emailo_user_id_903083_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(
                fields=["owner", "created_at"], name="farm_farm_owner_i_2eb40a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(
                fields=["farm_code"], name="farm_farm_farm_co_3059c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="animal",
            index=models.Index(
                fields=["farm", "health_status"], name="farm_animal_farm_id_5d660d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="field",
            index=models.Index(fields=["farm"], name="farm_field_farm_id_60d59c_idx"),
        ),
        migrations.AddIndex(
            model_name="field",
            index=models.Index(
                fields=["latitude", "longitude"], name="farm_field_latitud_a94ea7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="field",
            constraint=models.UniqueConstraint(
                fields=("farm", "name"), name="uniq_field_name_per_farm"
            ),
        ),
        migrations.AddIndex(
            model_name="crop",
            index=models.Index(
                fields=["field", "status"], name="farm_crop_field_i_6dd44c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["farm", "date"], name="farm_activi_farm_id_67f628_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["activity_type"], name="farm_activi_activit_98f01b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="yieldrecord",
            index=models.Index(
                fields=["farm", "crop_type"], name="farm_yieldr_farm_id_28fdd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="yieldrecord",
            index=models.Index(fields=["season"], name="farm_yieldr_season_5ff04c_idx"),
        ),
        migrations.AddIndex(
            model_name="yieldrecord",
            index=models.Index(
                fields=["irrigation_type"], name="farm_yieldr_irrigat_79414b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="yieldrecord",
            index=models.Index(
                fields=["soil_type"], name="farm_yieldr_soil_ty_472650_idx"
            ),
        ),
    ]
