# Generated by Django 5.2.9 on 2026-04-15 13:29

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="bbox_max_lat",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="bbox_max_lon",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="bbox_min_lat",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="bbox_min_lon",
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Farm center latitude",
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Farm center longitude",
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="polygon",
            field=models.JSONField(
                blank=True,
                help_text="Farm border polygon as [[lon, lat], ...]. Auto-closed on save.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="polygon",
            field=models.JSONField(
                blank=True,
                help_text="Field polygon as [[lon, lat], ...]. Auto-closed on save.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="farm",
            index=models.Index(
                fields=["latitude", "longitude"], name="farm_farm_latitud_d5b499_idx"
            ),
        ),
    ]
