# Generated by Django 5.2.9 on 2026-02-21 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0002_field_latitude_field_location_text_field_longitude"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="emailotp",
            name="farm_emailo_email_64db76_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailotp",
            name="farm_emailo_user_id_916c8b_idx",
        ),
        migrations.AddField(
            model_name="emailotp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("VERIFY_EMAIL", "VERIFY_EMAIL"),
                    ("RESET_PASSWORD", "RESET_PASSWORD"),
                ],
                db_index=True,
                default="VERIFY_EMAIL",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(
                fields=["email", "purpose", "used", "-created_at"],
                name="farm_emailo_email_1c3cba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(
                fields=["user", "purpose", "-created_at"],
                name="farm_emailo_user_id_cbce86_idx",
            ),
        ),
    ]
