# Generated by Django 5.2.9 on 2026-04-14 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="open-meteo", max_length=50)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("forecast_date", models.DateField()),
                (
                    "rain_next_24h_mm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "rain_next_72h_mm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "max_rain_probability_24h",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "evapotranspiration_24h",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "avg_temperature_24h",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_snapshots",
                        to="farm.field",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IrrigationRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("water_now", "Water Now"),
                            ("water_later", "Water Later"),
                            ("skip_rain_expected", "Skip: Rain Expected"),
                            ("skip_soil_wet", "Skip: Soil Already Wet"),
                            ("drainage_warning", "Drainage Warning"),
                            ("watch", "Watch"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("recommendation", models.TextField()),
                ("reason", models.TextField(blank=True)),
                (
                    "recommended_time",
                    models.CharField(
                        blank=True,
                        help_text="Example: early_morning, evening, after_rain, none",
                        max_length=50,
                    ),
                ),
                (
                    "rain_next_24h_mm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "rain_next_72h_mm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "evapotranspiration_24h",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irrigation_recommendations",
                        to="farm.field",
                    ),
                ),
                (
                    "weather_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="irrigation_recommendations",
                        to="weather.weathersnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="weathersnapshot",
            index=models.Index(
                fields=["field", "-created_at"], name="weather_wea_field_i_9f3514_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weathersnapshot",
            index=models.Index(
                fields=["forecast_date"], name="weather_wea_forecas_539cc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weathersnapshot",
            index=models.Index(fields=["source"], name="weather_wea_source_5b32a9_idx"),
        ),
        migrations.AddIndex(
            model_name="irrigationrecommendation",
            index=models.Index(
                fields=["field", "-created_at"], name="weather_irr_field_i_326389_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="irrigationrecommendation",
            index=models.Index(fields=["status"], name="weather_irr_status_ba07be_idx"),
        ),
        migrations.AddIndex(
            model_name="irrigationrecommendation",
            index=models.Index(
                fields=["severity"], name="weather_irr_severit_9179e6_idx"
            ),
        ),
    ]
