# Generated by Django 5.2.9 on 2026-04-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="irrigationrecommendation",
            name="rain_next_7d_mm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="weathersnapshot",
            name="rain_next_7d_mm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="irrigationrecommendation",
            name="recommended_time",
            field=models.CharField(
                blank=True,
                help_text="Example: early_morning, evening, after_rain, none",
                max_length=100,
            ),
        ),
    ]
