# Generated by Django 5.0.4 on 2026-04-11 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "polygon",
                    models.JSONField(
                        help_text="List of [longitude, latitude] pairs. Polygon will be auto-closed."
                    ),
                ),
                ("center_lat", models.FloatField(editable=False)),
                ("center_lon", models.FloatField(editable=False)),
                ("bbox_min_lon", models.FloatField(editable=False)),
                ("bbox_max_lon", models.FloatField(editable=False)),
                ("bbox_min_lat", models.FloatField(editable=False)),
                ("bbox_max_lat", models.FloatField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NDVIRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("ndvi_mean", models.FloatField()),
                ("ndvi_min", models.FloatField(blank=True, null=True)),
                ("ndvi_max", models.FloatField(blank=True, null=True)),
                ("ndvi_std", models.FloatField(blank=True, null=True)),
                ("evi_mean", models.FloatField(blank=True, null=True)),
                ("tcg_mean", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("bare", "Bare / no vegetation"),
                            ("poor", "Poor"),
                            ("moderate", "Moderate"),
                            ("healthy", "Healthy"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("synthetic", "Synthetic"),
                            ("huggingface", "HuggingFace"),
                            ("sentinel_api", "Sentinel API"),
                        ],
                        default="synthetic",
                        max_length=20,
                    ),
                ),
                ("cloud_coverage", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ndvi_records",
                        to="ndvi.field",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["field", "date"], name="ndvi_ndvire_field_i_d122d2_idx"
                    ),
                    models.Index(fields=["date"], name="ndvi_ndvire_date_5fbd00_idx"),
                ],
                "unique_together": {("field", "date")},
            },
        ),
    ]
