# Generated by Django 5.2.9 on 2026-04-15 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0001_initial"),
        ("ndvi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ndvirecord",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ndvi_records",
                to="farm.field",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ndvirecord",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="ndvirecord",
            index=models.Index(fields=["status"], name="ndvi_ndvire_status_695b8d_idx"),
        ),
        migrations.AddIndex(
            model_name="ndvirecord",
            index=models.Index(fields=["source"], name="ndvi_ndvire_source_6f549a_idx"),
        ),
        migrations.AddConstraint(
            model_name="ndvirecord",
            constraint=models.UniqueConstraint(
                fields=("field", "date"), name="uniq_ndvi_record_per_field_date"
            ),
        ),
        migrations.DeleteModel(
            name="Field",
        ),
    ]
